name: 'YAML to Outputs'
description:
  'This action will read in a YAML body / file and set them as outputs'
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'orange'

# Define your inputs here.
inputs:
  yaml:
    description:
      'The YAML body to parse and output. If this is set, the file input will be
      ignored.'
    required: false
  file:
    description: 'The path to the YAML file to parse and output.'
    required: false

# Define your outputs here.
outputs:
  generic: # output will be available to future steps
    description:
      'This command will have generic output variables based the issue body'

runs:
  using: node20
  main: dist/index.js
