name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          yaml: |
            foo:
              bar:
                - 1
                - 2
                - 3
            hello:
              world: abc
              example.com/foobar: bye
              'yes': true
              'no': false

      - name: Confirm outputs
        id: output
        run: |
          if [ "${{ steps.test-action.outputs['foo.bar[1]'] }}" != "2" ]; then
            echo "foo.bar[1] is not 2"
            exit 1
          fi

          if [ "${{ steps.test-action.outputs['hello.world'] }}" != "abc" ]; then
            echo "hello.world is not abc"
            exit 1
          fi

          if [ "${{ steps.test-action.outputs['hello["example.com/foobar"]'] }}" != "bye" ]; then
            echo "hello.example.com/foobar is not bye"
            exit 1
          fi
